// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE4_Idmoq6cRUXeN-_0tFfh2YN8D350J0',
    appId: '1:14380024514:web:58d869b0d9ad4dd88b715b',
    messagingSenderId: '14380024514',
    projectId: 'mobile-project-342dc',
    authDomain: 'mobile-project-342dc.firebaseapp.com',
    storageBucket: 'mobile-project-342dc.appspot.com',
    measurementId: 'G-NPT6TKTBEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwrItriUQbRxaFAROSjqFBC3IiEmqUhXU',
    appId: '1:14380024514:android:f000106a5b6e13018b715b',
    messagingSenderId: '14380024514',
    projectId: 'mobile-project-342dc',
    storageBucket: 'mobile-project-342dc.appspot.com',
  );
}
